### ISSUE TITLE
TwoWay coupling issue

### ISSUE THREAD

**Issue by danielabdi-noaa** [erf-model/ERF#1323] opened 2023-11-28 17:32 UTC
It seems that the two-way coupling option has issues. Results from a rising thermal buble problem (modified density current), I get correct results with one way coupling
![srtb-amrex-0029](https://github.com/erf-model/ERF/assets/52012304/731a556d-6cb1-4071-a626-aa6631b933b1)

Two-way coupling, on the other hand, seems to think that the level 1 grid has physical boundaries on the sides.
![srtb-amrex-twoway-0060](https://github.com/erf-model/ERF/assets/52012304/e102bd82-b095-430b-8f62-d14301db8165)

Unrelated to this issue: Is it possible to write "point data" to paraview file for better visualization?

**Comment by asalmgren** [comment] 2024-03-05 21:14
@danielabdi-noaa -- I'm going to close this issue -- hopefully the problem is fixed but let me know!

**Closed as completed by asalmgren** 2024-03-05 21:14 UTC

**Comment by danielabdi-noaa** [comment] 2024-03-06 03:31
@asalmgren Unfortunately I was not able to run correctly either the denisity current or the RTB problem posted here with "TwoWay" coupling option. Solution diverges quickly now, as opposed to the behaviour I described in this issue where the coupling boundary acts like a physical boundary. Let me know when you fix the density current test case I sent you. Thanks!
